#!/usr/bin/env python3
"""Regenerate namespace manifests from the package folders.

An author writes only the `bundles` section of `skills/<namespace>/manifest.yaml`.
This script fills in `schema_version`, `namespace` and `packages` from the
package folders, so the package inventory is never typed by hand and cannot
drift from what is published.

The `workspace` namespace is skipped: its manifest is generated by the
Workspace packager together with its provenance fields.

Usage:
  python3 scripts/generate_manifests.py          rewrite manifests in place
  python3 scripts/generate_manifests.py --check  report stale manifests, exit 1
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

NAME_PATTERN = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*")
VERSION_DIR = re.compile(r"v(\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.+-]+)?)")
GENERATED_ELSEWHERE = {"workspace"}
AUTHOR_KEYS = {"schema_version", "namespace", "packages", "bundles"}
HEADER = (
    "# The packages section is generated from the package folders by\n"
    "# `task manifest`. Edit only the bundles section, then run it again.\n"
)


class ManifestError(ValueError):
    pass


def current_packages(namespace_dir: Path) -> dict[str, str]:
    """Map each package to the version its `latest` alias points to."""
    packages = {}
    for package in sorted(namespace_dir.iterdir()):
        latest = package / "latest"
        if not package.is_dir() or package.is_symlink() or not latest.is_symlink():
            continue
        match = VERSION_DIR.fullmatch(latest.readlink().as_posix())
        if not match:
            raise ManifestError(f"{latest}: alias does not target an exact version directory")
        packages[package.name] = match.group(1)
    return packages


def read_bundles(manifest: Path) -> dict[str, list[str]]:
    try:
        document = yaml.safe_load(manifest.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as error:
        raise ManifestError(f"{manifest}: invalid YAML: {error}") from error
    if not isinstance(document, dict):
        raise ManifestError(f"{manifest}: must be a mapping")
    unknown = sorted(set(map(str, document)) - AUTHOR_KEYS)
    if unknown:
        raise ManifestError(f"{manifest}: unknown fields: {', '.join(unknown)}")
    bundles = document.get("bundles") or {}
    if not isinstance(bundles, dict):
        raise ManifestError(f"{manifest}: bundles must be a mapping")
    result = {}
    for bundle_id, bundle in bundles.items():
        if not isinstance(bundle_id, str) or not NAME_PATTERN.fullmatch(bundle_id):
            raise ManifestError(f"{manifest}: invalid bundle identifier {bundle_id!r}")
        members = bundle.get("packages") if isinstance(bundle, dict) else None
        if not isinstance(members, list) or not members or not all(isinstance(m, str) for m in members):
            raise ManifestError(f"{manifest}: bundle {bundle_id} needs a non-empty packages list")
        result[bundle_id] = members
    return result


def render(namespace: str, packages: dict[str, str], bundles: dict[str, list[str]]) -> str:
    lines = [HEADER.rstrip("\n"), "schema_version: 2", f"namespace: {namespace}", "packages:"]
    lines += [f'  {skill_id}: "{version}"' for skill_id, version in sorted(packages.items())]
    if bundles:
        lines.append("bundles:")
        for bundle_id in sorted(bundles):
            lines += [f"  {bundle_id}:", "    packages:"]
            lines += [f"      - {member}" for member in sorted(set(bundles[bundle_id]))]
    return "\n".join(lines) + "\n"


def generate(namespace_dir: Path) -> str | None:
    """Return the regenerated manifest, or None when the namespace has none."""
    manifest = namespace_dir / "manifest.yaml"
    if namespace_dir.name in GENERATED_ELSEWHERE or not manifest.is_file():
        return None
    packages = current_packages(namespace_dir)
    if not packages:
        raise ManifestError(f"{manifest}: namespace has no packages, so it must not have a manifest")
    bundles = read_bundles(manifest)
    for bundle_id, members in bundles.items():
        missing = sorted(set(members) - set(packages))
        if missing:
            raise ManifestError(
                f"{manifest}: bundle {bundle_id} names packages that are not published: {', '.join(missing)}"
            )
    return render(namespace_dir.name, packages, bundles)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--check", action="store_true", help="report stale manifests without writing")
    args = parser.parse_args(argv)

    skills = args.root / "skills"
    stale = []
    try:
        for namespace_dir in sorted(skills.iterdir()):
            if not namespace_dir.is_dir() or namespace_dir.is_symlink():
                continue
            expected = generate(namespace_dir)
            if expected is None:
                continue
            manifest = namespace_dir / "manifest.yaml"
            if manifest.read_text(encoding="utf-8") == expected:
                continue
            stale.append(manifest.relative_to(args.root).as_posix())
            if not args.check:
                manifest.write_text(expected, encoding="utf-8")
    except ManifestError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2

    if args.check:
        for path in stale:
            print(f"stale: {path}")
        return 1 if stale else 0
    for path in stale:
        print(f"updated: {path}")
    if not stale:
        print("all namespace manifests are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
